import 'package:flutter/material.dart';
import '../layout/main_layout.dart';
import '../utils/app_styles.dart';

class ContentApprovalQueueScreen extends StatelessWidget {
  const ContentApprovalQueueScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MainLayout(
      title: 'Content Approval',
      activeIndex: 6,
      child: const _ContentApprovalLayout(),
    );
  }
}

class _ContentApprovalLayout extends StatefulWidget {
  const _ContentApprovalLayout();

  @override
  State<_ContentApprovalLayout> createState() => _ContentApprovalLayoutState();
}

class _ContentApprovalLayoutState extends State<_ContentApprovalLayout> {
  int _tabIndex = 0; // "Pending Review" sub-tab

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: AppStyles.fidelityBackgroundDecoration(),
      child: Column(
        children: [
          _buildHeader(),
          Expanded(child: _buildMainContent()),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.fromLTRB(40, 48, 40, 0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Content Approval Queue',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 32,
                  fontWeight: FontWeight.bold,
                  letterSpacing: -0.5,
                ),
              ),
              ElevatedButton.icon(
                onPressed: () {},
                icon: const Icon(Icons.done_all, size: 18),
                label: const Text('Approve All Pending'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppStyles.accentRose,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          const Text(
            'Review, edit, and approve marketing assets generated by your AI agents.',
            style: TextStyle(color: AppStyles.mutedText, fontSize: 16),
          ),
          const SizedBox(height: 32),
          _buildTabs(),
        ],
      ),
    );
  }

  Widget _buildTabs() {
    final tabs = ['Pending Review', 'Approved', 'Needs Edit', 'Archived'];
    return Container(
      decoration: const BoxDecoration(
        border: Border(bottom: BorderSide(color: Colors.white10)),
      ),
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          children: tabs
              .asMap()
              .entries
              .map(
                (e) => InkWell(
                  onTap: () => setState(() => _tabIndex = e.key),
                  child: Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 32,
                      vertical: 20,
                    ),
                    decoration: BoxDecoration(
                      color: e.key == _tabIndex
                          ? Colors.white.withValues(alpha: 0.02)
                          : Colors.transparent,
                      border: Border(
                        bottom: BorderSide(
                          color: e.key == _tabIndex
                              ? AppStyles.accentRose
                              : Colors.transparent,
                          width: 2,
                        ),
                      ),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Text(
                          e.value,
                          style: TextStyle(
                            color: e.key == _tabIndex
                                ? Colors.white
                                : AppStyles.mutedText,
                            fontSize: 14,
                            fontWeight: e.key == _tabIndex
                                ? FontWeight.bold
                                : FontWeight.normal,
                          ),
                        ),
                        if (e.key == 0) ...[
                          const SizedBox(width: 8),
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                            decoration: BoxDecoration(
                              color: const Color(0xFFC05A5A).withValues(alpha: 0.2),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            child: const Text(
                              '4',
                              style: TextStyle(
                                color: Color(0xFFC05A5A),
                                fontSize: 11,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ],
                      ],
                    ),
                  ),
                ),
              )
              .toList(),
        ),
      ),
    );
  }

  Widget _buildMainContent() {
    return ListView(
      padding: const EdgeInsets.all(40),
      children: [
        _buildContentItem(
          itemType: 'Social Media Post',
          platform: 'Instagram',
          title: 'Just Listed: 4500 Ocean Avenue',
          agent: 'Marketing Bot v2',
          snippet: 'Breathtaking ocean views await! 🌊 This stunning 4 bed, 3 bath home just hit the market. Don\'t miss out on luxury coastal living...',
          imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=400',
          timeAgo: '2 hours ago',
        ),
        const SizedBox(height: 24),
        _buildContentItem(
          itemType: 'Email Newsletter',
          platform: 'Mailchimp',
          title: 'May Market Update for Investors',
          agent: 'Content Writer Pro',
          snippet: 'Subject: Q2 Real Estate Trends You Need to Know\n\nHi [Name],\nAs we enter the second quarter, the commercial real estate market is showing signs of...',
          timeAgo: '5 hours ago',
        ),
        const SizedBox(height: 24),
        _buildContentItem(
          itemType: 'Property Description',
          platform: 'MLS',
          title: '1120 Maple Street Description update',
          agent: 'Listing Optimizer',
          snippet: 'Nestled in the heart of the historic district, this meticulously restored craftsman combines timeless charm with modern amenities. Hardwood floors...',
          timeAgo: 'Yesterday',
        ),
      ],
    );
  }

  Widget _buildContentItem({
    required String itemType,
    required String platform,
    required String title,
    required String agent,
    required String snippet,
    String? imageUrl,
    required String timeAgo,
  }) {
    return Container(
      decoration: AppStyles.premiumCardDecoration(
        color: Colors.black.withValues(alpha: 0.2),
      ),
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(24),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if (imageUrl != null) ...[
                  ClipRRect(
                    borderRadius: BorderRadius.circular(8),
                    child: Image.network(
                      imageUrl,
                      width: 120,
                      height: 120,
                      fit: BoxFit.cover,
                    ),
                  ),
                  const SizedBox(width: 24),
                ],
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                                decoration: BoxDecoration(
                                  color: Colors.white.withValues(alpha: 0.05),
                                  borderRadius: BorderRadius.circular(4),
                                  border: Border.all(color: Colors.white10),
                                ),
                                child: Text(
                                  itemType,
                                  style: const TextStyle(
                                    color: Colors.white,
                                    fontSize: 11,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              ),
                              const SizedBox(width: 12),
                              Text(
                                'Platform: $platform',
                                style: const TextStyle(color: AppStyles.mutedText, fontSize: 13),
                              ),
                            ],
                          ),
                          Text(
                            timeAgo,
                            style: const TextStyle(color: AppStyles.mutedText, fontSize: 12),
                          ),
                        ],
                      ),
                      const SizedBox(height: 16),
                      Text(
                        title,
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Generated by: $agent',
                        style: const TextStyle(color: AppStyles.copperBrush, fontSize: 13),
                      ),
                      const SizedBox(height: 16),
                      Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: Colors.black.withValues(alpha: 0.3),
                          borderRadius: BorderRadius.circular(8),
                          border: Border.all(color: Colors.white.withValues(alpha: 0.05)),
                        ),
                        child: Text(
                          snippet,
                          style: const TextStyle(color: AppStyles.mutedText, fontSize: 14, height: 1.5),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          const Divider(height: 1, color: Colors.white10),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                TextButton.icon(
                  onPressed: () {},
                  icon: const Icon(Icons.edit_outlined, size: 18),
                  label: const Text('Edit Content'),
                  style: TextButton.styleFrom(
                    foregroundColor: Colors.white,
                  ),
                ),
                const SizedBox(width: 16),
                OutlinedButton.icon(
                  onPressed: () {},
                  icon: const Icon(Icons.close, size: 16),
                  label: const Text('Reject'),
                  style: OutlinedButton.styleFrom(
                    foregroundColor: const Color(0xFFC05A5A),
                    side: const BorderSide(color: Color(0xFFC05A5A)),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                  ),
                ),
                const SizedBox(width: 16),
                ElevatedButton.icon(
                  onPressed: () {},
                  icon: const Icon(Icons.check, size: 16),
                  label: const Text('Approve & Publish'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppStyles.statusGreen.withValues(alpha: 0.2),
                    foregroundColor: AppStyles.statusGreen,
                    elevation: 0,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                    side: BorderSide(color: AppStyles.statusGreen.withValues(alpha: 0.5)),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}