import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../layout/main_layout.dart';
import '../utils/app_styles.dart';
import '../services/recommendation_service.dart';
import '../models/recommendation_models.dart';

class ContentApprovalQueueScreen extends StatelessWidget {
  const ContentApprovalQueueScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MainLayout(
      title: 'Content Approval',
      activeIndex: 6,
      child: const _ContentApprovalLayout(),
    );
  }
}

class _ContentApprovalLayout extends StatefulWidget {
  const _ContentApprovalLayout();

  @override
  State<_ContentApprovalLayout> createState() => _ContentApprovalLayoutState();
}

class _ContentApprovalLayoutState extends State<_ContentApprovalLayout> {
  int _tabIndex = 0; // "Pending Review" sub-tab
  final RecommendationService _recommendationService = RecommendationService();
  final String _userId = Supabase.instance.client.auth.currentUser?.id ?? '';

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: AppStyles.fidelityBackgroundDecoration(),
      child: Column(
        children: [
          _buildHeader(),
          Expanded(child: _buildMainContent()),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.fromLTRB(40, 48, 40, 0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Content Approval Queue',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 32,
                  fontWeight: FontWeight.bold,
                  letterSpacing: -0.5,
                ),
              ),
              StreamBuilder<List<QueueItem>>(
                stream: _recommendationService.getAutomationQueueStream(_userId),
                builder: (context, snapshot) {
                  final pendingCount = snapshot.data?.where((item) => item.status == 'pending').length ?? 0;
                  return ElevatedButton.icon(
                    onPressed: pendingCount > 0 ? () {
                      // Logic for bulk approval could go here
                    } : null,
                    icon: const Icon(Icons.done_all, size: 18),
                    label: Text('Approve All Pending ($pendingCount)'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppStyles.accentRose,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                    ),
                  );
                }
              ),
            ],
          ),
          const SizedBox(height: 12),
          const Text(
            'Review, edit, and approve marketing assets generated by your AI agents.',
            style: TextStyle(color: AppStyles.mutedText, fontSize: 16),
          ),
          const SizedBox(height: 32),
          _buildTabs(),
        ],
      ),
    );
  }

  Widget _buildTabs() {
    final tabs = ['Pending Review', 'Approved', 'Needs Edit', 'Archived'];
    return Container(
      decoration: const BoxDecoration(
        border: Border(bottom: BorderSide(color: Colors.white10)),
      ),
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          children: tabs
              .asMap()
              .entries
              .map(
                (e) => InkWell(
                  onTap: () => setState(() => _tabIndex = e.key),
                  child: Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 32,
                      vertical: 20,
                    ),
                    decoration: BoxDecoration(
                      color: e.key == _tabIndex
                          ? Colors.white.withValues(alpha: 0.02)
                          : Colors.transparent,
                      border: Border(
                        bottom: BorderSide(
                          color: e.key == _tabIndex
                              ? AppStyles.accentRose
                              : Colors.transparent,
                          width: 2,
                        ),
                      ),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Text(
                          e.value,
                          style: TextStyle(
                            color: e.key == _tabIndex
                                ? Colors.white
                                : AppStyles.mutedText,
                            fontSize: 14,
                            fontWeight: e.key == _tabIndex
                                ? FontWeight.bold
                                : FontWeight.normal,
                          ),
                        ),
                        if (e.key == 0) ...[
                          const SizedBox(width: 8),
                          StreamBuilder<List<QueueItem>>(
                            stream: _recommendationService.getAutomationQueueStream(_userId),
                            builder: (context, snapshot) {
                              final count = snapshot.data?.where((item) => item.status == 'pending').length ?? 0;
                              if (count == 0) return const SizedBox.shrink();
                              return Container(
                                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                decoration: BoxDecoration(
                                  color: const Color(0xFFC05A5A).withValues(alpha: 0.2),
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                child: Text(
                                  '$count',
                                  style: const TextStyle(
                                    color: Color(0xFFC05A5A),
                                    fontSize: 11,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              );
                            }
                          ),
                        ],
                      ],
                    ),
                  ),
                ),
              )
              .toList(),
        ),
      ),
    );
  }

  Widget _buildMainContent() {
    return StreamBuilder<List<QueueItem>>(
      stream: _recommendationService.getAutomationQueueStream(_userId),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator(color: AppStyles.accentRose));
        }

        if (snapshot.hasError) {
          return Center(child: Text('Error: ${snapshot.error}', style: const TextStyle(color: Colors.white)));
        }

        final allItems = snapshot.data ?? [];
        final filteredItems = _filterItems(allItems);

        if (filteredItems.isEmpty) {
          return Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.inbox_outlined, size: 64, color: AppStyles.mutedText.withValues(alpha: 0.5)),
                const SizedBox(height: 16),
                Text(
                  'No items in ${_getTabName()}',
                  style: const TextStyle(color: AppStyles.mutedText, fontSize: 18),
                ),
              ],
            ),
          );
        }

        return ListView.builder(
          padding: const EdgeInsets.all(40),
          itemCount: filteredItems.length,
          itemBuilder: (context, index) {
            final item = filteredItems[index];
            return Padding(
              padding: const EdgeInsets.only(bottom: 24),
              child: _buildContentItem(item),
            );
          },
        );
      },
    );
  }

  List<QueueItem> _filterItems(List<QueueItem> items) {
    switch (_tabIndex) {
      case 0: // Pending Review
        return items.where((item) => item.status == 'pending').toList();
      case 1: // Approved
        return items.where((item) => 
          item.status == 'scheduled' || 
          item.status == 'processing' || 
          item.status == 'completed'
        ).toList();
      case 3: // Archived
        return items.where((item) => item.status == 'rejected' || item.status == 'failed').toList();
      default:
        return [];
    }
  }

  String _getTabName() {
    return ['Pending Review', 'Approved', 'Needs Edit', 'Archived'][_tabIndex];
  }

  Widget _buildContentItem(QueueItem item) {
    // Map QueueItem to UI fields
    final itemType = _getItemType(item.promotionId);
    final platform = _getPlatform(item.promotionId);
    final agent = 'AI Agent ${item.promotionId.split('_').first}';
    final timeAgo = _formatTimeAgo(item.queuedAt);
    final statusColor = _getStatusColor(item.status);

    return Container(
      decoration: AppStyles.premiumCardDecoration(
        color: Colors.black.withValues(alpha: 0.2),
      ),
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(24),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  width: 80,
                  height: 80,
                  decoration: BoxDecoration(
                    color: Colors.white.withValues(alpha: 0.05),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: Colors.white10),
                  ),
                  child: Center(
                    child: Icon(
                      _getIcon(item.promotionId),
                      color: AppStyles.accentRose,
                      size: 32,
                    ),
                  ),
                ),
                const SizedBox(width: 24),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                                decoration: BoxDecoration(
                                  color: Colors.white.withValues(alpha: 0.05),
                                  borderRadius: BorderRadius.circular(4),
                                  border: Border.all(color: Colors.white10),
                                ),
                                child: Text(
                                  itemType,
                                  style: const TextStyle(
                                    color: Colors.white,
                                    fontSize: 11,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              ),
                              const SizedBox(width: 12),
                              Text(
                                'Platform: $platform',
                                style: const TextStyle(color: AppStyles.mutedText, fontSize: 13),
                              ),
                            ],
                          ),
                          Text(
                            timeAgo,
                            style: const TextStyle(color: AppStyles.mutedText, fontSize: 12),
                          ),
                        ],
                      ),
                      const SizedBox(height: 16),
                      Text(
                        item.promotionTitle,
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Row(
                        children: [
                          Text(
                            'Generated by: $agent',
                            style: const TextStyle(color: AppStyles.copperBrush, fontSize: 13),
                          ),
                          const Spacer(),
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                            decoration: BoxDecoration(
                              color: statusColor.withValues(alpha: 0.1),
                              borderRadius: BorderRadius.circular(4),
                              border: Border.all(color: statusColor.withValues(alpha: 0.3)),
                            ),
                            child: Text(
                              item.status.toUpperCase(),
                              style: TextStyle(
                                color: statusColor,
                                fontSize: 10,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          const Divider(height: 1, color: Colors.white10),
          if (item.status == 'pending')
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton.icon(
                    onPressed: () {},
                    icon: const Icon(Icons.edit_outlined, size: 18),
                    label: const Text('Review Workflow'),
                    style: TextButton.styleFrom(
                      foregroundColor: Colors.white,
                    ),
                  ),
                  const SizedBox(width: 16),
                  const Text(
                    'Waiting for Admin Approval',
                    style: TextStyle(color: AppStyles.mutedText, fontSize: 13, fontStyle: FontStyle.italic),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  String _getItemType(String promotionId) {
    if (promotionId.contains('linkedin')) return 'Social Media Post';
    if (promotionId.contains('tiktok')) return 'Video Reel';
    if (promotionId.contains('email')) return 'Email Newsletter';
    return 'Marketing Asset';
  }

  String _getPlatform(String promotionId) {
    if (promotionId.contains('linkedin')) return 'LinkedIn';
    if (promotionId.contains('tiktok')) return 'TikTok';
    if (promotionId.contains('instagram')) return 'Instagram';
    if (promotionId.contains('email')) return 'Email';
    return 'Social Media';
  }

  IconData _getIcon(String promotionId) {
    if (promotionId.contains('linkedin')) return Icons.business;
    if (promotionId.contains('tiktok')) return Icons.play_circle_fill;
    if (promotionId.contains('email')) return Icons.email;
    return Icons.auto_awesome;
  }

  Color _getStatusColor(String status) {
    switch (status) {
      case 'pending': return Colors.orange;
      case 'scheduled': return Colors.blue;
      case 'processing': return Colors.purple;
      case 'completed': return Colors.green;
      case 'failed': return Colors.red;
      case 'rejected': return Colors.redAccent;
      default: return Colors.grey;
    }
  }

  String _formatTimeAgo(DateTime dateTime) {
    final now = DateTime.now();
    final difference = now.difference(dateTime);
    if (difference.inMinutes < 60) return '${difference.inMinutes}m ago';
    if (difference.inHours < 24) return '${difference.inHours}h ago';
    return '${difference.inDays}d ago';
  }
}
